name: "Build Release"
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
jobs:
  build-release:
    uses: StrikerRockers-Mods/.github/.github/workflows/build-release-fabric.yml@main
    secrets: inherit
    with:
      fabric-cf-id: 308976
      modrinth-id: wyaOz4TN
